name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # For PyPI trusted publishing (preferred)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build sdist/wheel
        run: |
          python -m build
      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
